POST https://kaliningrad.hh.ru/applicant/resumes/touch HTTP/1.1
content-type: text/html; charset=utf-8

{
    "resume": "735f57f7ff019943eb0039ed1f373444773568",
    "undirectable": "true"
}
###
GET https://api.hh.ru/vacancies?text=JavaScript&schedule=remote


